development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV["DEV_DB_NAME"] %>
  pool: 5
  username: <%= ENV["DEV_DB_USERNAME"] %>
  password: <%= ENV["DEV_DB_PASSWORD"] %>
  host: <%= ENV['DEV_DB_HOST'] %>
  port: <%= ENV['DEV_DB_PORT'] %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV["TEST_DB_NAME"] %>
  pool: 5
  username: <%= ENV["TEST_DB_USERNAME"] %>
  password: <%= ENV["TEST_DB_PASSWORD"] %>
  host: <%= ENV['TEST_DB_HOST'] %>
  port: <%= ENV['TEST_DB_PORT'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV["PROD_DB_NAME"] %>
  pool: 5
  username: <%= ENV["PROD_DB_USERNAME"] %>
  password: <%= ENV["PROD_DB_PASSWORD"] %>
  host: <%= ENV['PROD_DB_HOST'] %>
  port: <%= ENV['PROD_DB_PORT'] %>